export const models = [
  'gpt-4.1',
  'gpt-4o',
  'gpt-4o-audio-preview',
  'chatgpt-4o'
] as ('gpt-4.1' |'gpt-4o' | 'gpt-4o-audio-preview' | 'chatgpt-4o')[];

export const agentTypes = [
  'research',
  'code'
] as ('research' | 'code')[];

export const technologies = [
  'ActiveMQ',
  'Angular',
  'Ansible',
  'Apache',
  'Apache Kafka',
  'Apollo Client',
  'ASP.NET Core',
  'AWS',
  'Azure',
  'C#',
  'C++',
  'Cassandra',
  'CircleCI',
  'CockroachDB',
  'CouchDB',
  'Cypress',
  'Dart',
  'DigitalOcean',
  'Django',
  'Docker',
  'DynamoDB',
  'Elixir',
  'Elasticsearch',
  'Esbuild',
  'Express.js',
  'FastAPI',
  'Firebase',
  'Flask',
  'Flutter',
  'Gatsby',
  'Git',
  'GitHub Actions',
  'GitLab CI',
  'Go',
  'Google Cloud Platform',
  'Grafana',
  'GraphQL',
  'gRPC',
  'HAProxy',
  'Heroku',
  'Ionic',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'Kotlin',
  'Kubernetes',
  'Laravel',
  'Loki',
  'MariaDB',
  'Mocha',
  'MongoDB',
  'MySQL',
  'NATS',
  'NativeScript',
  'Next.js',
  'Nginx',
  'Node.js',
  'NumPy',
  'Nuxt.js',
  'Oracle Database',
  'Pandas',
  'Parcel',
  'Phoenix',
  'PHP',
  'Playwright',
  'Postgres',
  'Prometheus',
  'Python',
  'PyTorch',
  'RabbitMQ',
  'React',
  'React Native',
  'Redis',
  'REST API',
  'Redux',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'Scala',
  'Scikit-learn',
  'Selenium',
  'socket.io',
  'Spring Boot',
  'SQLite',
  'SQL Server',
  'Svelte',
  'Swift',
  'Symfony',
  'TensorFlow',
  'Terraform',
  'Travis CI',
  'TypeScript',
  'Varnish',
  'Vite',
  'Vue.js',
  'WebSocket',
  'Webpack',
  'Xamarin',
  'ZeroMQ'
];